import { type FormDocument, formDocumentSchema } from "./document";

/**
 * A document containing one of every element type, laid out on one A4 page.
 *
 * This is the Slice 1 proof of the coordinate system: the same object renders
 * in the browser now, and must render identically through headless Chromium at
 * Slice 5. It is also the most convenient fixture for every later slice, so it
 * lives in the schema package rather than in the web app.
 *
 * Coordinates are hand-placed in page units (794 x 1123) on a 40-unit margin.
 */
const document = {
  schemaVersion: 1,
  id: "doc_sample",
  title: "Membership application",
  pages: [
    {
      id: "page_1",
      background: "#ffffff",
      elements: [
        // --- watermark -----------------------------------------------------
        // Rotated and translucent, behind everything (z: 0). Proves rotation
        // and opacity survive the coordinate system unchanged.
        {
          id: "el_watermark",
          type: "text",
          content: "DRAFT",
          x: 130,
          y: 430,
          w: 540,
          h: 150,
          rotation: -28,
          z: 0,
          style: {
            fontFamily: "playfair-display",
            fontSize: 132,
            fontWeight: 700,
            color: "#0f172a",
            opacity: 0.06,
            align: "center",
            verticalAlign: "middle",
          },
        },

        // --- header --------------------------------------------------------
        {
          id: "el_logo",
          type: "image",
          objectKey: null,
          alt: "Organisation logo",
          fit: "contain",
          x: 40,
          y: 40,
          w: 120,
          h: 64,
          rotation: 0,
          z: 1,
          style: {
            fill: "#f1f5f9",
            stroke: "#cbd5e1",
            strokeWidth: 1,
            radius: 6,
          },
        },
        {
          id: "el_title",
          type: "text",
          content: "Membership application",
          x: 180,
          y: 44,
          w: 574,
          h: 36,
          rotation: 0,
          z: 1,
          style: {
            fontFamily: "playfair-display",
            fontSize: 28,
            fontWeight: 700,
            color: "#0f172a",
          },
        },
        {
          id: "el_subtitle",
          type: "text",
          content:
            "Please complete every field marked required. We respond within five working days.",
          x: 180,
          y: 82,
          w: 574,
          h: 22,
          rotation: 0,
          z: 1,
          style: { fontSize: 12, color: "#64748b" },
        },
        {
          id: "el_rule",
          type: "divider",
          color: "#e2e8f0",
          thickness: 1,
          x: 40,
          y: 120,
          w: 714,
          h: 1,
          rotation: 0,
          z: 1,
          style: {},
        },

        // --- identity ------------------------------------------------------
        {
          id: "el_name",
          type: "textInput",
          inputType: "text",
          label: "Full name",
          placeholder: "Ada Lovelace",
          required: true,
          validation: { minLength: 2, maxLength: 120 },
          x: 40,
          y: 146,
          w: 350,
          h: 66,
          rotation: 0,
          z: 1,
          style: {},
        },
        {
          id: "el_email",
          type: "textInput",
          inputType: "email",
          label: "Email address",
          placeholder: "ada@example.com",
          help: "We only use this to contact you about your application.",
          required: true,
          x: 404,
          y: 146,
          w: 350,
          h: 66,
          rotation: 0,
          z: 1,
          style: {},
        },
        {
          id: "el_address",
          type: "textarea",
          label: "Postal address",
          placeholder: "Street, city, postcode",
          required: false,
          x: 40,
          y: 226,
          w: 714,
          h: 104,
          rotation: 0,
          z: 1,
          style: {},
        },
        {
          id: "el_age",
          type: "number",
          label: "Age",
          placeholder: "18",
          step: 1,
          required: true,
          validation: { min: 16, max: 120 },
          x: 40,
          y: 344,
          w: 170,
          h: 66,
          rotation: 0,
          z: 1,
          style: {},
        },
        {
          id: "el_dob",
          type: "date",
          label: "Date of birth",
          required: true,
          validation: { maxDate: "2010-01-01" },
          x: 224,
          y: 344,
          w: 240,
          h: 66,
          rotation: 0,
          z: 1,
          style: {},
        },
        {
          id: "el_country",
          type: "select",
          label: "Country",
          placeholder: "Choose a country",
          required: true,
          options: [
            { id: "opt_gb", label: "United Kingdom", value: "gb" },
            { id: "opt_bd", label: "Bangladesh", value: "bd" },
            { id: "opt_other", label: "Somewhere else", value: "other" },
          ],
          x: 478,
          y: 344,
          w: 276,
          h: 66,
          rotation: 0,
          z: 1,
          style: {},
        },

        // Conditional on the country select. Slice 1 renders it unconditionally
        // — a design preview shows what was built, not what a filler would see.
        {
          id: "el_country_other",
          type: "textInput",
          inputType: "text",
          label: "Which country?",
          required: false,
          conditional: {
            targetId: "el_country",
            operator: "equals",
            value: "other",
          },
          x: 40,
          y: 424,
          w: 350,
          h: 66,
          rotation: 0,
          z: 1,
          style: {},
        },

        // --- preferences ---------------------------------------------------
        {
          id: "el_contact_pref",
          type: "radioGroup",
          label: "Preferred contact method",
          required: true,
          layout: "vertical",
          options: [
            { id: "opt_email", label: "Email", value: "email" },
            { id: "opt_post", label: "Post", value: "post" },
            { id: "opt_phone", label: "Telephone", value: "phone" },
          ],
          x: 404,
          y: 424,
          w: 350,
          h: 106,
          rotation: 0,
          z: 1,
          style: {},
        },
        {
          id: "el_interests",
          type: "checkboxGroup",
          label: "Interests",
          required: false,
          layout: "vertical",
          validation: { maxSelected: 2 },
          help: "Choose up to two.",
          options: [
            { id: "opt_talks", label: "Talks and lectures", value: "talks" },
            { id: "opt_work", label: "Workshops", value: "workshops" },
            { id: "opt_vol", label: "Volunteering", value: "volunteering" },
          ],
          x: 40,
          y: 504,
          w: 350,
          h: 120,
          rotation: 0,
          z: 1,
          style: {},
        },

        // --- shapes --------------------------------------------------------
        {
          id: "el_shape_rect",
          type: "shape",
          shape: "rect",
          x: 404,
          y: 548,
          w: 76,
          h: 60,
          rotation: 0,
          z: 1,
          style: {
            fill: "#dbeafe",
            stroke: "#3b82f6",
            strokeWidth: 2,
            radius: 8,
          },
        },
        {
          id: "el_shape_ellipse",
          type: "shape",
          shape: "ellipse",
          x: 494,
          y: 548,
          w: 76,
          h: 60,
          rotation: 0,
          z: 1,
          style: { fill: "#fee2e2", stroke: "#ef4444", strokeWidth: 2 },
        },
        {
          id: "el_shape_line",
          type: "shape",
          shape: "line",
          x: 584,
          y: 576,
          w: 76,
          h: 4,
          rotation: 0,
          z: 1,
          style: { stroke: "#0f172a", strokeWidth: 2 },
        },
        {
          id: "el_shape_arrow",
          type: "shape",
          shape: "arrow",
          x: 674,
          y: 576,
          w: 80,
          h: 4,
          rotation: 0,
          z: 1,
          style: { stroke: "#0f172a", strokeWidth: 2 },
        },

        // --- declarations --------------------------------------------------
        {
          id: "el_terms",
          type: "checkbox",
          label: "Declaration",
          boxLabel: "I confirm the information above is accurate.",
          required: true,
          x: 40,
          y: 642,
          w: 714,
          h: 58,
          rotation: 0,
          z: 1,
          style: {},
        },
        {
          id: "el_signature",
          type: "signature",
          label: "Signature",
          required: true,
          help: "Sign with a mouse, trackpad or finger.",
          x: 40,
          y: 714,
          w: 350,
          h: 130,
          rotation: 0,
          z: 1,
          style: {},
        },
        {
          id: "el_proof",
          type: "fileUpload",
          label: "Proof of address",
          multiple: false,
          required: false,
          validation: {
            maxSizeBytes: 5_000_000,
            acceptedTypes: ["application/pdf", "image/png", "image/jpeg"],
          },
          help: "PDF, PNG or JPEG, up to 5 MB.",
          x: 404,
          y: 714,
          w: 350,
          h: 130,
          rotation: 0,
          z: 1,
          style: {},
        },

        // --- footer --------------------------------------------------------
        {
          id: "el_footer_rule",
          type: "divider",
          color: "#e2e8f0",
          thickness: 1,
          x: 40,
          y: 1040,
          w: 714,
          h: 1,
          rotation: 0,
          z: 1,
          style: {},
        },
        {
          id: "el_footer",
          type: "text",
          content: "Formcraft — page 1 of 1",
          x: 40,
          y: 1052,
          w: 714,
          h: 20,
          rotation: 0,
          z: 1,
          style: {
            fontSize: 11,
            color: "#94a3b8",
            align: "center",
            fontFamily: "jetbrains-mono",
          },
        },
      ],
    },
  ],
};

/**
 * Parsed at module load, so a fixture that stops matching the schema fails
 * immediately and loudly rather than at the first render.
 */
export const sampleDocument: FormDocument = formDocumentSchema.parse(document);
